---
abstract: 'A Task module for DWIM Perl L<http://dwimperl.com/>'
author:
  - 'Gabor Szabo <szabgab@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-DWIM-Test
no_index:
  directory:
    - inc
    - t
requires:
  Test::Assert: 0.0504
  Test::Base: 0.60
  Test::Class: 0.36
  Test::DatabaseRow: 2.02
  Test::Deep: 0.108
  Test::Differences: 0.61
  Test::Distribution: 2.00
  Test::Exception: 0.31
  Test::Fatal: 0.010
  Test::HTTP::Server::Simple: 0.11
  Test::Harness: 0
  Test::LeakTrace: 0.14
  Test::LongString: 0.15
  Test::Manifest: 1.23
  Test::Memory::Cycle: 1.04
  Test::Mock::LWP: 0.06
  Test::MockModule: 0.05
  Test::MockObject: 1.20110612
  Test::Most: 0.25
  Test::NoWarnings: 1.03
  Test::Object: 0.07
  Test::Output: 1.01
  Test::Perl::Critic: 1.02
  Test::Pod: 1.45
  Test::Pod::Coverage: 1.08
  Test::Reporter: 1.58
  Test::Reporter::Transport::Metabase: 1.999008
  Test::Requires: 0.06
  Test::Script: 1.07
  Test::SharedFork: 0.19
  Test::Simple: 0.88
  Test::SubCalls: 1.09
  Test::TCP: 1.15
  Test::Taint: 1.04
  Test::Tester: 0.107
  Test::TinyMocker: 0.03
  Test::Trap: 0.2.1
  Test::Unit::Lite: 0.12
  Test::WWW::Mechanize: 1.38
  Test::WWW::Mechanize::Catalyst: 0
  Test::WWW::Selenium: 1.32
  Test::Warn: 0.24
  Test::Without::Module: 0.17
  Test::use::ok: 0.02
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dwimperl/Task-DWIM
version: 0.06
